const customers = [
    [
        'Jane Cooper',
        'Microsoft',
        '(225) 555-0118',
        'jane@microsoft.com',
        'United States',
        'Active',
    ],
    [
        'Floyd Miles',
        'Yahoo',
        '(205) 555-0100',
        'floyd@yahoo.com',
        'Kiribati',
        'Inactive',
    ],
    [
        'Ronald Richards',
        'Adobe',
        '(302) 555-0107',
        'ronald@adobe.com',
        'Israel',
        'Inactive',
    ],
    [
        'Marvin McKinney',
        'Tesla',
        '(252) 555-0126',
        'marvin@tesla.com',
        'Iran',
        'Active',
    ],
    [
        'Jerome Bell',
        'Google',
        '(629) 555-0129',
        'jerome@google.com',
        'Réunion',
        'Active',
    ],
    [
        'Kathryn Murphy',
        'Microsoft',
        '(406) 555-0120',
        'kathryn@microsoft.com',
        'Curaçao',
        'Active',
    ],
    [
        'Jacob Jones',
        'Yahoo',
        '(208) 555-0112',
        'jacob@yahoo.com',
        'Brazil',
        'Active',
    ],
    [
        'Kristin Watson',
        'Facebook',
        '(704) 555-0127',
        'kristin@facebook.com',
        'Åland Islands',
        'Inactive',
    ],
    [
        'Linda Nguyen',
        'Apple',
        '(415) 555-0105',
        'linda@apple.com',
        'United Kingdom',
        'Active',
    ],
    [
        'Marko Jović',
        'Samsung',
        '(387) 555-0109',
        'marko@samsung.com',
        'Serbia',
        'Inactive',
    ],
    [
        'Anna Schmidt',
        'Amazon',
        '(202) 555-0115',
        'anna@amazon.com',
        'Germany',
        'Active',
    ],
    [
        'Carlos Reyes',
        'Microsoft',
        '(503) 555-0113',
        'carlos@microsoft.com',
        'Mexico',
        'Inactive',
    ],
    [
        'Elena Petrova',
        'Google',
        '(749) 555-0102',
        'elena@google.com',
        'Russia',
        'Active',
    ],
    [
        'Ahmed Khan',
        'Facebook',
        '(92) 555-0108',
        'ahmed@facebook.com',
        'Pakistan',
        'Inactive',
    ],
    [
        'Sophie Dubois',
        'Apple',
        '(33) 555-0116',
        'sophie@apple.com',
        'France',
        'Active',
    ],
    [
        'Pavel Novák',
        'Tesla',
        '(420) 555-0123',
        'pavel@tesla.com',
        'Czech Republic',
        'Inactive',
    ],
    [
        'Luis Morales',
        'Amazon',
        '(51) 555-0124',
        'luis@amazon.com',
        'Peru',
        'Active',
    ],
    [
        'Maja Andersen',
        'Samsung',
        '(45) 555-0121',
        'maja@samsung.com',
        'Denmark',
        'Active',
    ],
    [
        'Yuki Tanaka',
        'Toyota',
        '(81) 555-0111',
        'yuki@toyota.com',
        'Japan',
        'Inactive',
    ],
    [
        'Mateo Silva',
        'Facebook',
        '(598) 555-0114',
        'mateo@facebook.com',
        'Uruguay',
        'Active',
    ],
    [
        'Leila Khan',
        'Google',
        '(92) 555-0128',
        'leila@google.com',
        'Pakistan',
        'Active',
    ],
    [
        'Andreas Müller',
        'BMW',
        '(49) 555-0110',
        'andreas@bmw.com',
        'Germany',
        'Inactive',
    ],
    [
        'Jorge Fernandez',
        'Amazon',
        '(54) 555-0122',
        'jorge@amazon.com',
        'Argentina',
        'Active',
    ],
    [
        'Anastasia Ivanova',
        'Microsoft',
        '(7) 555-0106',
        'anastasia@microsoft.com',
        'Russia',
        'Inactive',
    ],
]

export default customers
